# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'phillmac/ipfs-masonry-publish'
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
          $(tag)

    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'phillmac/ipfs-masonry-publish'
        command: 'push'
        tags: |
          latest
          $(tag)
